### ISSUE TITLE
API Key menu doen't open when clicked on sidebar

### ISSUE THREAD

**Issue by Owen-Griffin** [WillofSteel-Devs/app#29]
Steps to reproduce
- Launch app
- Enter API key and submit (if not already done)
- attempt to open the API key frame via the sidebar

This makes the only way to change your API key via editing the text file, which I assume isn't indented.

**Comment by ItsNeil17** [comment]
This is not the intended behavior. This happened due to me removing `api_key_frame` from the App class with commit 

`https://github.com/WillofSteel-Devs/app/commit/7e77ccad06b783d9afd23efbd441e09091abd321#diff-d252bc93f4be132397c96d9eb762d27a52aba9457d1c99d3cb0bc7f4ac18473aL27` (codeblocks required so GitHub doesn't format the commit, please copy & paste)
